sudo: required
language: node_js
node_js:
- "stable"
addons:
  chrome: beta
services:
- docker
env:
  - PAGE=http://127.0.0.1:8080
script:
  - npm run lint
  - npm run test
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
  - npm run system-test:start-server
  - npm run system-test:full-run
  - npm run docker:build
  - npm run docker:system-test:run
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; npm run docker:push ; fi
