sudo: required
language: node_js
node_js:
- "stable"
services:
- docker
script:
  - set -e # This makes build to fail on first error
  - yarn run lint
  - yarn run test
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
  - yarn run docker:build
  - yarn run docker:system-test:run
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; yarn run docker:push ; fi
